title: 'Bla Bli Blog'
languageCode: 'en-us'
params:
  description: 'Description.'
  author: 'Author.'
menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 1
      pre: <i class="fa-solid fa-hashtag"></i>
permalinks:
  posts: 'post/:year/:month/:day/:slug/'
markup:
  highlight:
    style: 'dracula'
