title: "Bla Bli Blog"
languageCode: "en-US"
baseURL: https://blabli.blog
canonifyURLs: true
disableKinds: "section"
params:
  description: "The personal blog of stffffn"
  author: "stffffn"
  images:
    - default-feature-image.png
menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 1
      pre: <i class="fa-solid fa-hashtag"></i>
    - identifier: rss
      name: RSS
      url: /index.xml
      weight: 2
      pre: <i class="fa-solid fa-square-rss"></i>
  social:
    - identifier: github
      name: GitHub
      url: https://github.com/stffffn
      pre: <i class="fa-brands fa-github"></i>
    - identifier: mastodon
      name: Mastodon
      url: https://mastodon.social/@stffffn
      pre: <i class="fa-brands fa-mastodon"></i>
permalinks:
  posts: "post/:year/:month/:day/:slug/"
markup:
  highlight:
    style: "doom-one"
