name: Deploy to Github Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true
      - name: Build
        run: hugo --minify
      - name: Add .nojekyll
        run: touch .nojekyll
      - name: Add CNAME
        run: echo blabli.blog >> CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: public
